# program
REPEATMASKER: "~/opt/biosoft/RepeatMasker/RepeatMasker"
BRAKER: "~/opt/biosoft/BRAKER_v2.1.0/braker.pl"
Glimmer: "~/opt/biosoft/GlimmerHMM/bin/glimmerhmm_linux_x86_64"
GlimmerHMM: "~/opt/biosoft/GlimmerHMM/trained_dir/arabidopsis/"
BLAST_BIN: "~/opt/biosoft/ncbi-blast-2.7.1+/bin/"
PASA_DIR: "~/opt/biosoft/PASApipeline/"
EVIDENCE_DIR: "~/opt/biosoft/EVidenceModeler-1.1.1/"
TRANSDECODE: "~/opt/biosoft/TransDecoder-v5.3.0"


SAMPLES: "samples.txt"
SPECIES: "cocculata"
